name: veilid
version: 0.1.5
description: Veilid Framework
homepage: https://veilid.com
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ffi: ^2.0.0
  change_case: ^1.0.1
  path_provider: ^2.0.9
  path: ^1.8.0
  system_info2: ^3.0.2
  charcode: ^1.3.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.veilid.veilid
        pluginClass: VeilidPlugin
      ios:
        pluginClass: VeilidPlugin
      linux:
        pluginClass: VeilidPlugin
      macos:
        pluginClass: VeilidPlugin
      windows:
        pluginClass: VeilidPlugin
      web:
        pluginClass: VeilidPluginStubWeb
        fileName: veilid_plugin_stub_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - assets/foo.wasm
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
