name: veilid_test
description: A library for testing Veilid applications
version: 0.1.0
publish_to: none
# repository: https://gitlab.com/veilid/dart_veilid_test

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  async_tools: ^0.1.6
  veilid:
    path: ../..

dev_dependencies:
  lint_hard: ^4.0.0
  test: ^1.24.0
